version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 132456
      MYSQL_DATABASE: softwarehouse
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
